services:
  db:
    build: .
    ulimits:
      nofile:
        soft: 1048576
        hard: 1048576
    container_name: databases_mysql
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: community
      MYSQL_ROOT_PASSWORD: root1234
    volumes:
      - /home/tingwuren/Documents/IdeaProjects/community/mysql-config/my.cnf:/etc/mysql/my.cnf
